version: '3'
services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: santepsy
      POSTGRES_PASSWORD: santepsy
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U santepsy"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    image: santepsy:latest
    command: sh -c "npm run migrate; npm run seed; npm run test;"
    environment:
      DATABASE_URL: postgres://santepsy:santepsy@db:5432/santepsy
      SECRET_LOGS: "production_value_should_be_set_in_.env"
      SECRET: "production_value_should_be_set_in_.env"
      SPEED_LIMITATION: "false"
    depends_on:
      db:
        condition: service_healthy