version: '3'
services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: santepsy
      POSTGRES_PASSWORD: santepsy
    ports:
      - "5432:5432"
  back:
    image: santepsy-back:latest
    command: sh -c "npm run dev; npm run migrate; npm run seed;"
    environment:
      DATABASE_URL: postgres://santepsy:santepsy@db:5432/santepsy
      SECRET_LOGS: "production_value_should_be_set_in_.env"
      SECRET: "production_value_should_be_set_in_.env"
      SPEED_LIMITATION: "false"
    depends_on:
      - db
  front:
    image: santepsy-front:latest
    command: sh -c "npm run cy:ci"