name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          tags: santepsy:latest
          outputs: type=docker,dest=/tmp/santepsy.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: santepsy
          retention-days: 1
          path: /tmp/santepsy.tar

  test-back:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: santepsy
          path: /tmp
      - name: Load Docker image
        run: docker load --input /tmp/santepsy.tar
      - name: Tests
        run: docker-compose -f ./docker/docker-compose-for-backend.yml up --abort-on-container-exit;

  test-integration:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download back artifact
        uses: actions/download-artifact@v2
        with:
          name: santepsy
          path: /tmp
      - name: Load Docker image
        run: docker load --input /tmp/santepsy.tar
      - name: Tests
        run: docker-compose -f ./docker/docker-compose-for-integration.yml up --abort-on-container-exit;
      - name: Archive test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress
          retention-days: 1
          path: |
            frontend/cypress/screenshots
            frontend/cypress/videos

  linter:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download back artifact
        uses: actions/download-artifact@v2
        with:
          name: santepsy
          path: /tmp
      - name: Load Docker image
        run: docker load --input /tmp/santepsy.tar
      - name: Linter
        run: docker-compose -f ./docker/docker-compose-for-linter.yml up --abort-on-container-exit;
